site_name: BotiCord API - Docs
docs_dir: './docs'
site_dir: './dist'

theme:
  name: material
  custom_dir: './overrides/'
  logo: https://boticord.top/static/new/logo-full-v2.svg
  favicon: https://boticord.top/static/new/logo-full-v2.svg
  language: ru
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - navigation.sections
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: kerdoku-dark
      toggle:
        icon: material/white-balance-sunny
        name: Светлая тема
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/moon-waxing-crescent
        name: Тёмная тема

copyright: © 2020-2022 — BotiCord.top. Все права защищены.

markdown_extensions:
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true

extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://boticord.top
    - icon: fontawesome/brands/github
      link: https://github.com/boticord
    - icon: fontawesome/brands/discord
      link: https://boticord.top/discord

extra_css:
  - stylesheets/dark_theme.css

plugins:
  - search:
      lang: ru

nav:
  - Главная: index.md
  - Библиотеки:
      - Python: libraries/boticordpy.md
      - JS (TS): libraries/boticordjs.md
      - Rust: libraries/boticordrs.md
      - Java: libraries/boticordjava.md
      - .NET: libraries/boticordnet.md
      - Dart: libraries/boticorddart.md
  - Методы:
      - Боты: methods/bots.md
      - Сервера: methods/servers.md
      - Пользователи: methods/users.md
      - Ссылки: methods/links.md
  - Веб-хуки: webhooks.md
  - Тематическое:
      - Переход на v2: topics/v1vsv2.md
